### ISSUE TITLE
Auth middleware issue

### ISSUE THREAD

**Issue by Reveurrr** [HavenShen/slim-born#10]
Hello, 

(Slim 4 Version)

When you go to an url like _http://localhost/auth/password/change_ and you are disconnected or vice versa when you try to go on a page like sign in when you are connected the following exeption appear : 
**Undefined variable $response** in **AuthMiddleware.php** or **GuestMiddleware.php**

**Comment by HavenShen** [comment]
Paste error message I have a look.

**Comment by alissonsilvas** [comment]
Hello, 

I have the same problem, was solved? @Reveurrr 

Warning: Undefined variable $response in /app/Middleware/AuthMiddleware.php on line 23

Fatal error: Uncaught Error: Call to a member function withRedirect() on null in path project.

**Comment by alissonsilvas** [comment]
Solved!

`$response = new Response();

 return $response->withHeader(
				'Location',
				$this->container->get('router')->urlFor('home')
			)->withStatus(302);
`
